export const INFLATE_COMMENTS = 'INFLATE_COMMENTS';
export const START_EDIT_COMMENT = 'START_EDIT_COMMENT';
export const SAVE_COMMENT = 'SAVE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const ADD_VOTE_SCORE_TO_COMMENT = 'ADD_VOTE_SCORE_TO_COMMENT';

export const INFLATE_CATEGORIES = 'INFLATE_CATEGORIES';
export const INFLATE_POSTS = 'INFLATE_POSTS';
export const ADD_VOTE_SCORE_TO_POST = 'ADD_VOTE_SCORE_TO_POST';
export const DELETE_POST = 'DELETE_POST';
export const START_EDIT_POST = 'START_EDIT_POST';
export const SAVE_POST = 'SAVE_POST';

export const CYCLE_LIST_ORDER = 'CYCLE_LIST_ORDER';
export const SHOW_CONFIRM = 'SHOW_CONFIRM';
export const HIDE_CONFIRM = 'HIDE_CONFIRM';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const SHOW_DRAWER = 'SHOW_DRAWER';
export const TOGGLE_COMMENT_DATE_PICKER = 'TOGGLE_COMMENT_DATE_PICKER';
